# Generated by Django 5.2.7 on 2026-05-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_title', models.CharField(default='Issue Report', max_length=80)),
                ('location', models.CharField(max_length=500)),
                ('issue_description', models.TextField(max_length=500)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('completion_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('rejected', 'Rejected'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_id', models.CharField(default='TEMP0001', editable=False, max_length=8, unique=True)),
                ('department', models.TextField(default='Manual', max_length=30)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('allocated_to', models.TextField(blank=True, max_length=10)),
                ('appeal_status', models.CharField(choices=[('not_appealed', 'Not Appealed'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='not_appealed', max_length=20)),
                ('trust_score_delta', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
    ]
