# Generated by Django 5.2.7 on 2026-05-11 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='report.issuereport'),
        ),
    ]
