# Generated by Django 5.2.7 on 2026-02-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_issuereport_dislikes_issuereport_likes_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='appeal_status',
            field=models.CharField(blank=True, default='not_appealed', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='trust_score_delta',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
