# Generated by Django 5.2.7 on 2026-02-14 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_issuereport_dislikes_issuereport_likes_comment'),
        ('users', '0004_emailotp_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deactivated_until',
            field=models.DateTimeField(blank=True, help_text='User is temporarily deactivated until this time', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='trust_score',
            field=models.IntegerField(default=100, help_text='User trust score (0-110)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='auth_method',
            field=models.CharField(choices=[('email', 'Email/JWT'), ('google', 'Google OAuth')], default='email', help_text='Primary authentication method used for account creation', max_length=10),
        ),
        migrations.CreateModel(
            name='TrustScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='Change in trust score (can be negative)')),
                ('reason', models.TextField(help_text='Reason for trust score change')),
                ('appeal_status', models.CharField(choices=[('not_appealed', 'Not Appealed'), ('pending', 'Appeal Pending'), ('approved', 'Appeal Approved'), ('rejected', 'Appeal Rejected')], default='not_appealed', max_length=20)),
                ('admin_id', models.IntegerField(blank=True, help_text='Admin user ID who made the change', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(blank=True, help_text='Associated report if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.issuereport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_score_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trust Score Log',
                'verbose_name_plural': 'Trust Score Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
