# Generated by Django 5.2.7 on 2026-02-14 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_incentive_reward_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='trust_score',
            field=models.IntegerField(default=100, help_text='User trust score (0-110)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(110)]),
        ),
    ]
